### ISSUE TITLE
How can we use RouterProvider from react-router ?

### ISSUE THREAD

**Issue by afkcodes** [cyrus01337/vite-offline-localhost-boilerplate#1]
Hello  Cyrus this is an awesome repro, i was trying to use routerProvider from react-router but it seems to through an error. also seeing blank page when i see blank page when using `<BrowserRouter>` component. Any help would be great.

**Comment by cyrus01337** [comment]
Hey @afkcodes, thank you man. If this is still an issue (hopefully not), what error did you receive? Any reproducible code you could send would help in identifying the problem.

**Comment by afkcodes** [comment]
Hey @cyrus01337 i think i have figured it out, the thing is BrowserRouter will not work as it rewrites the route to `/` where there is a need of server, but it hash router it is not the case.

**Comment by afkcodes** [comment]
There are some things i wanted to ask, about the vite config. 

1. Why we have kept the following config for server & preview

```
  server: {
    host: true,
    port: 3000,
  },
  preview: {
    host: true,
    port: 3000,
  },
```

**Comment by cyrus01337** [comment]
Port 3000 is comfortable for me during development, host is for broadcasting as I tend to swap between multiple devices on the same network. Does this get in the way of anything?

**Comment by afkcodes** [comment]
can you please explain. the experimental `renderBuiltUrl` what it does, as i am not able to understand it from the docs

```
experimental: {
    renderBuiltUrl: (filename) =>
      mode === 'production' ? `./${filename}` : { relative: true },
  },

basically the above config
```

**Comment by cyrus01337** [comment]
`renderBuiltUrl` determines how the filename should be generated when built, which is used in both development and production.

There is a need for this as the favicon was unable to be requested and used in production, despite it working fine in development. ``./${filename}`` is used in production to point to the local file in `dist/`, whereas `{ relative: true }` is the default that the development server utilises if I'm not mistaken - I vaguely remember source-diving to find the default.

Visually it makes little sense for both to exist, but they allow the built URL to be defined in different relative ways, like pointing to the file via relative filepaths vs URLs (which I'm assuming is the difference).
